### ISSUE TITLE
[BUG] `hide-items`与`Scriptio`中的可选插件`to-contact-list-top`部分功能冲突

### ISSUE THREAD

**Issue by Lucas04-nhr** [PRO-2684/Transitio-user-css#21]
当同时开启题述两个插件时，倘若未开启隐藏左侧小红点的功能时，有概率出现左下角红点显示错误的问题（即把本该显示在邮箱右上角的红点也在向上箭头处显示），如图：
<img width="89" alt="Snipaste_2024-10-28_11-26-31@2x" src="https://github.com/user-attachments/assets/be8c0b15-1b8c-491e-b997-a23cee599036">

===

解决办法是可以在`hide-items.css`中添加下列样式表隐藏左下角菜单栏中所有红点：
```css
div.func-menu sub.q-badge-sub, 
div.func-menu sub.q-badge-dot,
div.func-menu sub.q-badge-dot__large,
div.func-menu sub.q-badge__red {
    display: none;
}
```

希望可以在`hide-item`中添加相关选项~
