### ISSUE TITLE
[Bug] `添加过渡动画`样式似乎没有生效

### ISSUE THREAD

**Issue by QingFeng-awa** [PRO-2684/Transitio-user-css#7]
在旧版本(在加载器还没有显示版本的功能的时候),`添加过度动画`样式是正常的,但在更新(这个样式)后这个样式就不起作用了。
我尝试禁用所有插件和脚本只启用这个一个插件和这一个样式,但这个脚本仍然不起作用。
![image](https://github.com/PRO-2684/Transitio-user-css/assets/151742581/43e7d95f-6ed3-4178-b941-9756063697e7)

**Comment by PRO-2684** [comment]
看一下插件数据目录下的配置文件 `config.json`, 以及此样式的代码文件

**Comment by QingFeng-awa** [comment]
`config.json`
```json
{
    "styles": {
        "C://Program Files/LiteLoaderQQNT/data/transitio/styles/compact-at-list.css": {
            "enabled": true,
            "variables": {}
        },
        "C://Program Files/LiteLoaderQQNT/data/transitio/styles/image-viewer.css": {
            "enabled": true,
            "variables": {}
        },
        "C://Program Files/LiteLoaderQQNT/data/transitio/styles/lite-tools-recall-enhancement.css": {
            "enabled": true,
            "variables": {}
        },
        "C://Program Files/LiteLoaderQQNT/data/transitio/styles/no-update-dot.css": {
            "enabled": true,
            "variables": {}
        },
        "C://Program Files/LiteLoaderQQNT/data/transitio/styles/qqface-fine-tune.css": {
            "enabled": true,
            "variables": {}
        },
        "C://Program Files/LiteLoaderQQNT/data/transitio/styles/transition.css": {
            "enabled": true,
            "variables": {}
        },
        "C://Program Files/LiteLoaderQQNT/data/transitio/styles/transparent.css": {
            "enabled": true,
            "variables": {}
        },
        "C://Program Files/LiteLoaderQQNT/data/transitio/styles/q-tag-enhancement.css": {
            "enabled": true,
            "variables": {
                "box-shadow-opacity": "50"
            }
        },
        "C://Program Files/LiteLoaderQQNT/data/transitio/styles/link-color.css": {
            "enabled": true,
            "variables": {}
        },
        "C://Program Files/LiteLoaderQQNT/data/transitio/styles/hide-items.css": {
            "enabled": true,
            "variables": {}
        }
    }
}
```

**Comment by QingFeng-awa** [comment]
`transition.css`
```css
/* ==UserStyle==
@name           Transition
@description    添加过渡动画
@preprocessor   transitio
@version        0.1.1
@homepageURL    https://github.com/PRO-2684/Transitio-user-css/#transition
@author         PRO-2684
@license     	gpl-3.0
@var number duration "过渡时间 (s)" "0.2, 0.01, 2, 0.01"
==/UserStyle== */
/* 背景颜色 */
* {
    transition-property: background, border, box-shadow;
    transition-duration: var(--duration) s;
    transition-timing-function: ease-in-out;
    transition-delay: 0s;
}

i.q-icon {
    transition-property: color, background, border, box-shadow;
}

/* 侧栏图标背景 */
div.tab-item-mask {
    transition-property: background, opacity;

    &:hover {
        animation: none;
        opacity: 0.04 !important;
    }
}

/* 左侧聊天列表的字; 链接/艾特 */
.recent-contact-item.across-mode { /* 左侧聊天列表的字 */

    .list-item__title > div > span,
    .summary-main > div {
        transition-property: color;
    }
}

.text-element { /* 链接/艾特 */

    .text-element--at,
    .text-link {
        transition-property: color;
    }
}

a { /* 链接 */
    transition-property: color;
}

.radio-tab .radio-tab__item > span { /* 好友界面的 tab */
    transition-property: color, opacity !important;
    transition-duration: var(--duration) s !important;
    transition-timing-function: ease-in-out !important;
}

.operation .send { /* "发送" 按钮颜色（实际上是透明度） */
    transition-property: background, opacity;
}

/* 菜单动画 (Adapted from https://t.me/ntqqtweaks/14) */
@keyframes fadeIn {
    from {
        opacity: 0%;
        margin-top: 10px;
        margin-left: 3px;
    }
    to {
        opacity: 80%;
        margin-top: 0px;
        margin-left: 0px;
    }
}

.q-menu, .q-context-menu, .q-context-sub-menu__container, .q-tooltips__content, .q-float-card {
    animation: fadeIn var(--duration) s;
}

/* 消息动画 (Adapted from https://github.com/PRO-2684/Transitio-user-css/pull/1/commits/d81cab38e7d9a41936002ee96e830c30458895a8) */
@keyframes message-ltr {
    from {
        transform: translateX(-5em);
        opacity: 0%;
    }
    to {
        transform: translateX(0);
        opacity: 100%;
    }
}

@keyframes message-rtl {
    from {
        transform: translateX(5em);
        opacity: 0%;
    }
    to {
        transform: translateX(0);
        opacity: 100%;
    }
}

.ml-item > .message { /* @Shapaper: 添加贝塞尔曲线动效，使消息进入 Q 弹 */
    animation: message-ltr var(--duration) s cubic-bezier(.56, -0.37, .46, 1.58);

    &:has( .message-container--align-right) {
        animation-name: message-rtl;
    }
}
```
